//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Animal
    {
        [Key]
        public int id_animal { get; set; }
        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "Informe a descrição do animal")]
        public string ds_animal { get; set; }
    }
}
